[/]
color-scheme='prefer-dark'
document-font-name='JetBrains Mono 12'
font-name='JetBrains Mono 11'
gtk-key-theme='Default'
gtk-theme='Adwaita'
icon-theme='Papirus-Dark'
show-battery-percentage=false
toolkit-accessibility=false
